version: '3.3'

services:
   load-images:
      build:
         context: ./docker-builds/s4s-fhir-broker/dockerLoadImages
         dockerfile: Dockerfile
      image: rsna/load-images
      environment:
         - DEST_PACS=DCM4CHEE@dcm4chee-arc:11112
         - IMAGE_SET=smart-1288992
      networks:
         - internal
   load-ldap:
      build:
         context: ./docker-builds/s4s-fhir-broker/dockerLoadLdap
         dockerfile: Dockerfile
      image: rsna/load-ldap
      environment:
         - AE_TITLE=PACS-SCP
         - DEVICE_NAME=DCM-BROKER-SCP
         - DEVICE_HOST=dcmrs-broker
         - DEVICE_PORT=11122  
         - LDAP_HOST=slapd
         - LDAP_PORT=389
      networks:
         - internal
   load-reference-data:
      build:
         context: ./docker-builds/reference-data-load
         dockerfile: Dockerfile
      networks:
         - internal

networks:
   internal:
      driver: bridge
