version: '3.3'

services:
   slapd:
      ports:
         - "389:389"
   postgres:
      ports:
         - "5432:5432"
   dcm4chee-arc:
      ports:
         - "9090:8080"
         - "9990:9990"
         - "11112:11112"
         - "2575:2575"
   dcmrs-broker:
      ports:
         - "4567:4567"
         - "11122:11112"
   introspection-service:
      ports:
         - "9004:5000"
   s4s-fhir-broker:
      environment:
         - IMAGE_ARCHIVE_WADO_RS_URL="http://localhost:8080/baseDstu3"
      ports:
         - "8080:8080"
   rsnadb:
      ports:
         - "5433:5432"
